# Generated by Django 4.2 on 2023-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
